name: Convert Issue To Pull Request

on:
  issues:
    types:
      - opened

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: https://api.allocator.tech
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Convert Issue To PR
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "Converting Issue To PR with repo: $REPO_NAME"
          echo "Issue number: ${{ github.event.issue.number }}"
          curl --header "Content-Type: application/json" \
               --request POST \
               --data '{"issue_number": "'${{ github.event.issue.number }}'", "repo": "'$REPO_NAME'", "owner": "'${{ github.repository_owner }}'"}' \
               "${BACKEND_URL}/application"